name: 'Changelog Reminder'
description: 'If there is not a changelog in the PR add a comment to remind the committer'
author: 'GitHub'
branding:
  icon: 'check'
  color: 'green'
inputs:
  changelog_regex:
    description: "A regex to match changelog file, default to 'change_log\/.*\/*.yml'"

runs:
  using: 'node12'
  main: 'lib/main.js'
